name: Publish

on:
  push:
    tags: ["*"]
  
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            ext: dylib
            cc: cc
          - os: ubuntu-latest
            ext: so
            cc: cc
          - os: windows-latest
            ext: dll
            cc: x86_64-w64-mingw32-gcc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{runner.os == 'Linux'}}
      - name: Build lib
        run: |
          ${{ matrix.cc }} -fPIC -c -Isrc/ src/parser.c -o parser.o
          ${{ matrix.cc }} -fPIC -shared parser.o -o libtree-sitter-magik.${{ matrix.ext }}
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: libtree-sitter-magik-${{ runner.os }}
          path: libtree-sitter-magik*
          if-no-files-found: error

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: libtree-sitter-magik
          pattern: libtree-sitter-magik*
          merge-multiple: true
      - name: Zip artifacts
        run: |
          zip libtree-sitter-magik-macOS.zip libtree-sitter-magik.dylib
          zip libtree-sitter-magik-Linux.zip libtree-sitter-magik.so
          zip libtree-sitter-magik-Windows.zip libtree-sitter-magik.dll
      - uses: softprops/action-gh-release@v2
        with:
          files: libtree-sitter-magik-*.zip
